name: Build Storybook

# Run this workflow whenever there's a PR that is opened, synchronized, and repored
on: pull_request

jobs:
  # Label for build job
  build-storybook:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install package dependencies
        run: npm ci

      - name: Build storybook
        run: npm run build-storybook
